### PR TITLE
Check for duplicated dependencies in Travis

### PR DESCRIPTION
**Pull request by dtolnay**
This currently fails though. :crying_cat_face: 

```
bitflags v0.8.2
├── clap v2.24.2
│   └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx)
└── openssl v0.9.12
    └── native-tls v0.1.2
        └── hyper-native-tls v0.2.2
            └── reqwest v0.6.2
                └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx) (*)

bitflags v0.9.0
└── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx)

serde v0.9.15
└── ndarray v0.9.1
    └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx)

serde v1.0.7
├── chrono v0.3.1
│   └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx)
├── reqwest v0.6.2
│   └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx) (*)
├── serde_json v1.0.2
│   ├── reqwest v0.6.2 (*)
│   └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx) (*)
├── serde_urlencoded v0.5.1
│   └── reqwest v0.6.2 (*)
├── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx) (*)
└── toml v0.4.1
    └── stdx v0.117.0-rc (file:///home/travis/build/brson/stdx) (*)
```

### CODE REVIEW

**Comment by dtolnay** [comment]
Relevant ndarray issue: https://github.com/bluss/rust-ndarray/issues/314

**Comment by brson** [comment]
[bitflags](https://github.com/kbknapp/clap-rs/pull/966)

**Comment by brson** [comment]
I'm going to disable serde on ndarray for now.

**Comment by brson** [comment]
Rebased. No more serde dupe. Still waiting on clap.

**Pull request closed without merging**
